version: '3.4'

services:
  auction.server:
    # image: ${DOCKER_REGISTRY-}auctionserver
    image: auction-server
    container_name: auction.server
    build:
      context: .
      dockerfile: Auction.Server/Dockerfile
    ports:
        - "7287:7287"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:7287; #http://+:80 #443
        - ASPNETCORE_Kestrel__Certificates__Default__Password=test
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
        - ~/.aspnet/https:/https:ro
    networks:
        - auction.net
  auction.database:
    image: postgres:latest  
    container_name: auction.database
    environment:
        - POSTGRES_DB=AuctionDB
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=test
    # volumes:
        # - ./.containers/auction-db:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    networks:
        - auction.net
  auction.cache:
    image: redis:latest
    container_name: auction.cache
    restart: always
    ports:
        - '6379:6379'
    networks:
        - auction.net
  auction.client:
    image: auction-client
    container_name: auction.client
    build:
      context: ./Auction.Client
      dockerfile: dockerfile
    ports:
        - "4200:4200"
    networks:
        - auction.net
networks:
  auction.net:
    driver: bridge