# Use an official Node.js runtime as a parent image
FROM node:20.9.0-alpine

WORKDIR /app

# Copy package.json and package-lock.json to /app
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy app source code to /app
COPY . .

# Build the app for production
RUN npm run build --prod

# Expose port 80 for the container
EXPOSE 4200

# Start the app
CMD ["npm", "start"]

###########################

# FROM node:20.9.0-alpine

# WORKDIR /app

# COPY package*.json ./

# RUN npm install

# COPY . .

# RUN npm run build --prod

# EXPOSE 4200

# CMD /app/node_modules/.bin/ng serve --host 0.0.0.0 --disableHostCheck